=== LaszAndrea/ModernDB/DJ7PNE_0226/XMLSchemaDJ7PNE.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!--Egyszerű elemek-->

    <xs:element name="folyometer" type="xs:int" />
    <xs:element name="tipus" type="nyomtatotipTipus" />
    <xs:element name="festekfelhasznalas" type="felhasznTipusok" />
    <xs:element name="raszterhenger" type="raszterhengerTipus" />

    <xs:element name="lejarat" type="idoTipus" />
    <xs:element name="raktaron" type="felhasznTipusok" />
    <xs:element name="gyarto" type="xs:string" />

    <xs:element name="termeknev" type="xs:string" />
    <xs:element name="mennyiseg" type="felhasznTipusok" />
    <xs:element name="papirmin" type="felhasznTipusok" />

    <xs:element name="nev" type="xs:string" />
    <xs:element name="szarmazas" type="xs:string" />
    <xs:element name="isz" type="xs:int" />
    <xs:element name="utca" type="xs:string" />

    <xs:element name="telephely" type="xs:string" />
    <xs:element name="alapitas" type="xs:int" />

    <xs:element name="elkeszites" type="idoTipus" />
    <xs:element name="szinek" type="xs:string" />
    <xs:element name="tervezo" type="xs:string" />

    <xs:element name="szuletes" type="xs:int" />
    <xs:element name="szerzodese" type="xs:int"  />

    <xs:element name="rendeles" type="idoTipus" />

    <!--Saját típusok-->

    <xs:simpleType name="nyomtatotipTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="VF001" />
            <xs:enumeration value="VF002" />
            <xs:enumeration value="VF003" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="raszterhengerTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1][0-9][0-9]/[0-9]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idoTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([12]\d{3}.(0[1-9]|1[0-2]).(0[1-9]|[12]\d|3[01]))" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="felhasznTipusok">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="adoszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tajszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]" />
        </xs:restriction>
    </xs:simpleType>

    <!--Felépítés-->

    <xs:element name="tasakgyartas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nyomtatogep" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="folyometer" />
                            <xs:element ref="tipus" />
                            <xs:element ref="festekfelhasznalas" />
                            <xs:element ref="raszterhenger" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="termeknev" type="xs:string" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="festek" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="lejarat" />
                            <xs:element ref="raktaron" />
                            <xs:element ref="gyarto" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                        <xs:attribute name="pantonszam" type="felhasznTipusok" />
                        <xs:attribute name="felhasznalas" type="xs:string" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="tasakrendeles" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="termeknev" />
                            <xs:element ref="mennyiseg" />
                            <xs:element ref="papirmin" />
                        </xs:sequence>
                        <xs:attribute name="tasakID" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="vevo" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="nev" />
                            <xs:element ref="szarmazas" />
                            <xs:element name="telephely" minOccurs="1" maxOccurs="2">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="isz" />
                                        <xs:element ref="utca" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element> 
                        </xs:sequence>
                        <xs:attribute name="adoszam" type="adoszamTipus" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="gyar" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="nev" />
                            <xs:element ref="telephely" />
                            <xs:element ref="alapitas" />
                        </xs:sequence>
                        <xs:attribute name="gyAdoszam" type="adoszamTipus" />
                        <xs:attribute name="vGy" type="adoszamTipus" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="logo" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="elkeszites" />
                            <xs:element ref="szinek" minOccurs="1" maxOccurs="unbounded" />
                            <xs:element ref="tervezo" />
                        </xs:sequence>
                        <xs:attribute name="logoId" type="xs:int" />
                        <xs:attribute name="gyL" type="adoszamTipus" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="tulajdonos" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="nev" />
                            <xs:element ref="szuletes" />
                            <xs:element ref="szerzodese" />
                        </xs:sequence>
                        <xs:attribute name="tajszam" type="tajszamTipus" />
                        <xs:attribute name="tGy" type="adoszamTipus" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="szerzodes" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="rendeles" />
                        </xs:sequence>
                        <xs:attribute name="tNev" type="xs:string" />
                        <xs:attribute name="tasakID" type="xs:int" />
                        <xs:attribute name="adoszam" type="adoszamTipus" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <!--Kulcsok-->

        <xs:key name="nyomtatogep_kulcs">
            <xs:selector xpath="nyomtatogep" />
            <xs:field xpath="@termeknev" />
        </xs:key>

        <xs:key name="festek_kulcs">
            <xs:selector xpath="festek" />
            <xs:field xpath="@pantonszam" />
        </xs:key>

        <xs:key name="tasakrendeles_kulcs">
            <xs:selector xpath="tasakrendeles" />
            <xs:field xpath="@tasakID" />
        </xs:key>

        <xs:key name="vevo_kulcs">
            <xs:selector xpath="vevo" />
            <xs:field xpath="@adoszam" />
        </xs:key>

        <xs:key name="gyar_kulcs">
            <xs:selector xpath="gyar" />
            <xs:field xpath="@gyAdoszam" />
        </xs:key>

        <xs:key name="logo_kulcs">
            <xs:selector xpath="logo" />
            <xs:field xpath="@logoId" />
        </xs:key>

        <xs:key name="tulajdonos_kulcs">
            <xs:selector xpath="tulajdonos" />
            <xs:field xpath="@tajszam" />
        </xs:key>

        <!--Idegen kulcsok-->

        <xs:keyref refer="nyomtatogep_kulcs" name="nyomtatogep_idegen_kulcs">
            <xs:selector xpath="festek" />
            <xs:field xpath="@felhasznalas" />
        </xs:keyref>

        <xs:keyref refer="vevo_kulcs" name="vevo_idegen_kulcs">
            <xs:selector xpath="gyar" />
            <xs:field xpath="@vGy" />
        </xs:keyref>

        <xs:keyref refer="gyar_kulcs" name="gyar_tulajdonos_idegen_kulcs">
            <xs:selector xpath="tulajdonos" />
            <xs:field xpath="@tGy" />
        </xs:keyref>

        <xs:keyref refer="nyomtatogep_kulcs" name="szerzodes_nyomtatogep_idegen_kulcs">
            <xs:selector xpath="szerzodes" />
            <xs:field xpath="@tNev" />
        </xs:keyref>

        <xs:keyref refer="vevo_kulcs" name="szerzodes_vevo_idegen_kulcs">
            <xs:selector xpath="szerzodes" />
            <xs:field xpath="@adoszam" />
        </xs:keyref>

        <xs:keyref refer="tasakrendeles_kulcs" name="szerzodes_tasakrendeles_idegen_kulcs">
            <xs:selector xpath="szerzodes" />
            <xs:field xpath="@tasakID" />
        </xs:keyref>

        <!--1:1-->

        <xs:unique name="unique_logo">
            <xs:selector xpath="logo" />
            <xs:field xpath="@gyL" />
        </xs:unique>

    </xs:element>

</xs:schema>

=== LaszAndrea/ModernDB/DJ7PNE_0226/XMLDJ7PNE.xml
<?xml version="1.0" encoding="UTF-8"?>

<tasakgyartas xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaDJ7PNE.xsd">


    <!--Nyomtatógépek-->

    <nyomtatogep termeknev="1kg Gyermelyi finomliszt">
        <folyometer>2500</folyometer>
        <tipus>VF001</tipus>
        <festekfelhasznalas>5kg</festekfelhasznalas>
        <raszterhenger>180/10</raszterhenger>
        <raszterhenger>120/8</raszterhenger>
    </nyomtatogep>

    <nyomtatogep termeknev="2kg Hajdú búzadara">
        <folyometer>12000</folyometer>
        <tipus>VF001</tipus>
        <festekfelhasznalas>8kg</festekfelhasznalas>
        <raszterhenger>180/10</raszterhenger>
    </nyomtatogep>

    <nyomtatogep termeknev="5kg Auschan Optimum">
        <folyometer>20000</folyometer>
        <tipus>VF002</tipus>
        <festekfelhasznalas>14kg</festekfelhasznalas>
        <raszterhenger>120/8</raszterhenger>
        <raszterhenger>110/2</raszterhenger>
    </nyomtatogep>

    <!--Festékek-->

    <festek pantonszam="P1495" felhasznalas="1kg Gyermelyi finomliszt">
        <lejarat>2030.10.15</lejarat>
        <raktaron>150kg</raktaron>
        <gyarto>Colorprint</gyarto>
    </festek>

    <festek pantonszam="P706" felhasznalas="1kg Gyermelyi finomliszt">
        <lejarat>2032.08.01</lejarat>
        <raktaron>450kg</raktaron>
        <gyarto>Colorprint</gyarto>
        <gyarto>Poli-Farbe</gyarto>
    </festek>

    <festek pantonszam="P1400" felhasznalas="2kg Hajdú búzadara">
        <lejarat>2028.02.22</lejarat>
        <raktaron>150kg</raktaron>
        <gyarto>Colorprint</gyarto>
    </festek>

    <festek pantonszam="P632" felhasznalas="5kg Auschan Optimum">
        <lejarat>2024.07.19</lejarat>
        <raktaron>100kg</raktaron>
        <gyarto>Colorprint</gyarto>
    </festek>

    <festek pantonszam="P935" felhasznalas="5kg Auschan Optimum">
        <lejarat>2026.12.31</lejarat>
        <raktaron>50kg</raktaron>
        <gyarto>Colorprint</gyarto>
    </festek>

    <festek pantonszam="P1250" felhasznalas="5kg Auschan Optimum">
        <lejarat>2032.12.15</lejarat>
        <raktaron>80kg</raktaron>
        <gyarto>Colorprint</gyarto>
    </festek>

    <!--Tasakrendelések-->

    <tasakrendeles tasakID="1">
        <termeknev>1kg Gyermelyi finomliszt</termeknev>
        <mennyiseg>150000db</mennyiseg>
        <papirmin>80gr</papirmin>
    </tasakrendeles>

    <tasakrendeles tasakID="2">
        <termeknev>2kg Hajdú búzadara</termeknev>
        <mennyiseg>100000db</mennyiseg>
        <papirmin>70gr</papirmin>
    </tasakrendeles>

    <tasakrendeles tasakID="3">
        <termeknev>5kg Auschan Optimum</termeknev>
        <mennyiseg>50000db</mennyiseg>
        <papirmin>100gr</papirmin>
    </tasakrendeles>

    <!--Vevők-->

    <vevo adoszam="77777777-77-777777">
        <nev>Egyes cég</nev>
        <szarmazas>Magyarország</szarmazas>
        <telephely>
            <isz>4090</isz>
            <utca>Kossuth</utca>
        </telephely>
        <telephely>
            <isz>4090</isz>
            <utca>Bethlen</utca>
        </telephely>
    </vevo>

    <vevo adoszam="22222222-22-222222">
        <nev>Kettes cég</nev>
        <szarmazas>Magyarország</szarmazas>
        <telephely>
            <isz>3515</isz>
            <utca>Diósgyőri</utca>
        </telephely>
    </vevo>

    <vevo adoszam="88888888-22-787878">
        <nev>Hármas cég</nev>
        <szarmazas>Magyarország</szarmazas>
        <telephely>
            <isz>2080</isz>
            <utca>Petőfi</utca>
        </telephely>
    </vevo>

    <!--Gyárak-->

    <gyar gyAdoszam="12345678-22-654321" vGy="77777777-77-777777">
        <nev>Egyes gyár</nev>
        <telephely>Felsősima</telephely>
        <alapitas>2002</alapitas>
    </gyar>

    <gyar gyAdoszam="13151614-32-956348" vGy="77777777-77-777777">
        <nev>Kettes gyár</nev>
        <telephely>Miskolc</telephely>
        <alapitas>2008</alapitas>
    </gyar>

    <gyar gyAdoszam="32945817-68-164872" vGy="22222222-22-222222">
        <nev>Hármas gyár</nev>
        <telephely>Debrecen</telephely>
        <alapitas>2016</alapitas>
    </gyar>

    <gyar gyAdoszam="62599875-77-121212" vGy="88888888-22-787878">
        <nev>Négyes gyár</nev>
        <telephely>Debrecen</telephely>
        <alapitas>2018</alapitas>
    </gyar>

    <!--Logók-->

    <logo logoId="1" gyL="12345678-22-654321">
        <elkeszites>2001.12.15</elkeszites>
        <szinek>Piros</szinek>
        <szinek>Kék</szinek>
        <szinek>Zöld</szinek>
        <tervezo>Kiss Péter</tervezo>
    </logo>

    <logo logoId="2" gyL="13151614-32-956348">
        <elkeszites>2007.12.20</elkeszites>
        <szinek>Fehér</szinek>
        <szinek>Zöld</szinek>
        <tervezo>Nagy Zoltán</tervezo>
    </logo>

    <logo logoId="3" gyL="32945817-68-164872">
        <elkeszites>2016.02.08</elkeszites>
        <szinek>Vörös</szinek>
        <szinek>Fehér</szinek>
        <szinek>Fekete</szinek>
        <tervezo>Bogyó Annamária</tervezo>
    </logo>

    <logo logoId="4" gyL="62599875-77-121212">
        <elkeszites>2018.06.26</elkeszites>
        <szinek>Fehér</szinek>
        <szinek>Fekete</szinek>
        <tervezo>Varga Krisztina</tervezo>
    </logo>

    <!--Tulajdonosok-->

    <tulajdonos tajszam="119075100" tGy="12345678-22-654321">
        <nev>Terplán Zénó</nev>
        <szuletes>1982</szuletes>
        <szerzodese>2002</szerzodese>
    </tulajdonos>

    <tulajdonos tajszam="117080205" tGy="13151614-32-956348">
        <nev>Tóth László</nev>
        <szuletes>1970</szuletes>
        <szerzodese>1993</szerzodese>
    </tulajdonos>

    <tulajdonos tajszam="120154203" tGy="32945817-68-164872">
        <nev>Reszegi Ivett</nev>
        <szuletes>1969</szuletes>
        <szerzodese>2000</szerzodese>
    </tulajdonos>

    <tulajdonos tajszam="120005203" tGy="62599875-77-121212">
        <nev>Balogh Panna</nev>
        <szuletes>1993</szuletes>
        <szerzodese>2012</szerzodese>
    </tulajdonos>

    <!--Szerződés kapcsolat-->

    <szerzodes tNev="1kg Gyermelyi finomliszt" tasakID="1" adoszam="77777777-77-777777">
        <rendeles>2022.09.15</rendeles>
    </szerzodes>

    <szerzodes tNev="2kg Hajdú búzadara" tasakID="2" adoszam="77777777-77-777777">
        <rendeles>2022.09.18</rendeles>
    </szerzodes>

    <szerzodes tNev="5kg Auschan Optimum" tasakID="3" adoszam="88888888-22-787878">
        <rendeles>2022.10.06</rendeles>
    </szerzodes>

    <szerzodes tNev="5kg Auschan Optimum" tasakID="3" adoszam="22222222-22-222222">
        <rendeles>2022.10.03</rendeles>
    </szerzodes>

</tasakgyartas>
